-- =====================================================
-- Esta migración originalmente creaba la tabla `game_plans`
-- (Plan de Partido) referenciando `partidos(id)`, y añadía
-- `match_reports.partido_id` con la misma referencia.
--
-- La tabla `partidos` (004/005) fue sustituida por
-- `eventos_calendario` (011_eventos_calendario.sql) sin pasar
-- por una migración registrada, así que `partidos` no existe
-- en la base de datos real. `game_plans` y `match_reports.partido_id`
-- tampoco se llegaron a usar en ningún punto del frontend
-- (no hay referencias a `game_plans` ni a la tabla `partidos`
-- en frontend/src). Se deja este archivo vacío para no romper
-- el historial de migraciones ya aplicado.
-- =====================================================
