-- =====================================================
-- Seed: calendario completo JUVENIL PREFERENTE Grupo 2 - Huesca
-- (temporada 2026/2027, Fútbol Aragón — 10 equipos, 18 jornadas, 90 partidos)
-- Solo se inserta si la competición ya existe (dada de alta en COMPETICIONES)
-- y todavía no tiene calendario cargado (evita duplicados en reintentos).
-- =====================================================
DO $$
DECLARE
    v_competicion_id UUID;
BEGIN
    SELECT id INTO v_competicion_id FROM competiciones WHERE nombre = 'JUVENIL PREFERENTE Grupo 2 - Huesca' LIMIT 1;

    IF v_competicion_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM calendario_competicion WHERE competicion_id = v_competicion_id
    ) THEN
        INSERT INTO calendario_competicion (competicion_id, jornada, fecha, equipo_local, equipo_visitante) VALUES
        (v_competicion_id, 1, '2026-12-12', 'PEÑAS OSCENSES-C.D. Aramovil', 'BARBASTRO-U.D.'),
        (v_competicion_id, 1, '2026-12-12', 'HUESCA-S.D. ESCUELA DE FUTBOL', 'SOBRARBE-ESCUELA DEP.'),
        (v_competicion_id, 1, '2026-12-12', 'MONZON FUTBOL BASE - Mallazo', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"'),
        (v_competicion_id, 1, '2026-12-12', 'HUESCA-S.D.', 'JACETANO-C.F. Arok Sport'),
        (v_competicion_id, 1, '2026-12-12', 'ALMUDEVAR A.D.', 'BINEFAR-FUTBOL BASE'),
        (v_competicion_id, 2, '2026-12-19', 'BARBASTRO-U.D.', 'ALMUDEVAR A.D.'),
        (v_competicion_id, 2, '2026-12-19', 'SOBRARBE-ESCUELA DEP.', 'PEÑAS OSCENSES-C.D. Aramovil'),
        (v_competicion_id, 2, '2026-12-19', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"', 'HUESCA-S.D. ESCUELA DE FUTBOL'),
        (v_competicion_id, 2, '2026-12-19', 'JACETANO-C.F. Arok Sport', 'MONZON FUTBOL BASE - Mallazo'),
        (v_competicion_id, 2, '2026-12-19', 'BINEFAR-FUTBOL BASE', 'HUESCA-S.D.'),
        (v_competicion_id, 3, '2027-01-09', 'BARBASTRO-U.D.', 'SOBRARBE-ESCUELA DEP.'),
        (v_competicion_id, 3, '2027-01-09', 'PEÑAS OSCENSES-C.D. Aramovil', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"'),
        (v_competicion_id, 3, '2027-01-09', 'HUESCA-S.D. ESCUELA DE FUTBOL', 'JACETANO-C.F. Arok Sport'),
        (v_competicion_id, 3, '2027-01-09', 'MONZON FUTBOL BASE - Mallazo', 'BINEFAR-FUTBOL BASE'),
        (v_competicion_id, 3, '2027-01-09', 'ALMUDEVAR A.D.', 'HUESCA-S.D.'),
        (v_competicion_id, 4, '2027-01-16', 'SOBRARBE-ESCUELA DEP.', 'ALMUDEVAR A.D.'),
        (v_competicion_id, 4, '2027-01-16', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"', 'BARBASTRO-U.D.'),
        (v_competicion_id, 4, '2027-01-16', 'JACETANO-C.F. Arok Sport', 'PEÑAS OSCENSES-C.D. Aramovil'),
        (v_competicion_id, 4, '2027-01-16', 'BINEFAR-FUTBOL BASE', 'HUESCA-S.D. ESCUELA DE FUTBOL'),
        (v_competicion_id, 4, '2027-01-16', 'HUESCA-S.D.', 'MONZON FUTBOL BASE - Mallazo'),
        (v_competicion_id, 5, '2027-01-23', 'SOBRARBE-ESCUELA DEP.', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"'),
        (v_competicion_id, 5, '2027-01-23', 'BARBASTRO-U.D.', 'JACETANO-C.F. Arok Sport'),
        (v_competicion_id, 5, '2027-01-23', 'PEÑAS OSCENSES-C.D. Aramovil', 'BINEFAR-FUTBOL BASE'),
        (v_competicion_id, 5, '2027-01-23', 'HUESCA-S.D. ESCUELA DE FUTBOL', 'HUESCA-S.D.'),
        (v_competicion_id, 5, '2027-01-23', 'ALMUDEVAR A.D.', 'MONZON FUTBOL BASE - Mallazo'),
        (v_competicion_id, 6, '2027-01-30', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"', 'ALMUDEVAR A.D.'),
        (v_competicion_id, 6, '2027-01-30', 'JACETANO-C.F. Arok Sport', 'SOBRARBE-ESCUELA DEP.'),
        (v_competicion_id, 6, '2027-01-30', 'BINEFAR-FUTBOL BASE', 'BARBASTRO-U.D.'),
        (v_competicion_id, 6, '2027-01-30', 'HUESCA-S.D.', 'PEÑAS OSCENSES-C.D. Aramovil'),
        (v_competicion_id, 6, '2027-01-30', 'MONZON FUTBOL BASE - Mallazo', 'HUESCA-S.D. ESCUELA DE FUTBOL'),
        (v_competicion_id, 7, '2027-02-13', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"', 'JACETANO-C.F. Arok Sport'),
        (v_competicion_id, 7, '2027-02-13', 'SOBRARBE-ESCUELA DEP.', 'BINEFAR-FUTBOL BASE'),
        (v_competicion_id, 7, '2027-02-13', 'BARBASTRO-U.D.', 'HUESCA-S.D.'),
        (v_competicion_id, 7, '2027-02-13', 'PEÑAS OSCENSES-C.D. Aramovil', 'MONZON FUTBOL BASE - Mallazo'),
        (v_competicion_id, 7, '2027-02-13', 'ALMUDEVAR A.D.', 'HUESCA-S.D. ESCUELA DE FUTBOL'),
        (v_competicion_id, 8, '2027-02-27', 'ALMUDEVAR A.D.', 'JACETANO-C.F. Arok Sport'),
        (v_competicion_id, 8, '2027-02-27', 'BINEFAR-FUTBOL BASE', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"'),
        (v_competicion_id, 8, '2027-02-27', 'HUESCA-S.D.', 'SOBRARBE-ESCUELA DEP.'),
        (v_competicion_id, 8, '2027-02-27', 'MONZON FUTBOL BASE - Mallazo', 'BARBASTRO-U.D.'),
        (v_competicion_id, 8, '2027-02-27', 'HUESCA-S.D. ESCUELA DE FUTBOL', 'PEÑAS OSCENSES-C.D. Aramovil'),
        (v_competicion_id, 9, '2027-03-06', 'JACETANO-C.F. Arok Sport', 'BINEFAR-FUTBOL BASE'),
        (v_competicion_id, 9, '2027-03-06', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"', 'HUESCA-S.D.'),
        (v_competicion_id, 9, '2027-03-06', 'SOBRARBE-ESCUELA DEP.', 'MONZON FUTBOL BASE - Mallazo'),
        (v_competicion_id, 9, '2027-03-06', 'BARBASTRO-U.D.', 'HUESCA-S.D. ESCUELA DE FUTBOL'),
        (v_competicion_id, 9, '2027-03-06', 'PEÑAS OSCENSES-C.D. Aramovil', 'ALMUDEVAR A.D.'),
        (v_competicion_id, 10, '2027-03-13', 'BARBASTRO-U.D.', 'PEÑAS OSCENSES-C.D. Aramovil'),
        (v_competicion_id, 10, '2027-03-13', 'SOBRARBE-ESCUELA DEP.', 'HUESCA-S.D. ESCUELA DE FUTBOL'),
        (v_competicion_id, 10, '2027-03-13', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"', 'MONZON FUTBOL BASE - Mallazo'),
        (v_competicion_id, 10, '2027-03-13', 'JACETANO-C.F. Arok Sport', 'HUESCA-S.D.'),
        (v_competicion_id, 10, '2027-03-13', 'BINEFAR-FUTBOL BASE', 'ALMUDEVAR A.D.'),
        (v_competicion_id, 11, '2027-03-20', 'ALMUDEVAR A.D.', 'BARBASTRO-U.D.'),
        (v_competicion_id, 11, '2027-03-20', 'PEÑAS OSCENSES-C.D. Aramovil', 'SOBRARBE-ESCUELA DEP.'),
        (v_competicion_id, 11, '2027-03-20', 'HUESCA-S.D. ESCUELA DE FUTBOL', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"'),
        (v_competicion_id, 11, '2027-03-20', 'MONZON FUTBOL BASE - Mallazo', 'JACETANO-C.F. Arok Sport'),
        (v_competicion_id, 11, '2027-03-20', 'HUESCA-S.D.', 'BINEFAR-FUTBOL BASE'),
        (v_competicion_id, 12, '2027-04-03', 'SOBRARBE-ESCUELA DEP.', 'BARBASTRO-U.D.'),
        (v_competicion_id, 12, '2027-04-03', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"', 'PEÑAS OSCENSES-C.D. Aramovil'),
        (v_competicion_id, 12, '2027-04-03', 'JACETANO-C.F. Arok Sport', 'HUESCA-S.D. ESCUELA DE FUTBOL'),
        (v_competicion_id, 12, '2027-04-03', 'BINEFAR-FUTBOL BASE', 'MONZON FUTBOL BASE - Mallazo'),
        (v_competicion_id, 12, '2027-04-03', 'HUESCA-S.D.', 'ALMUDEVAR A.D.'),
        (v_competicion_id, 13, '2027-04-10', 'ALMUDEVAR A.D.', 'SOBRARBE-ESCUELA DEP.'),
        (v_competicion_id, 13, '2027-04-10', 'BARBASTRO-U.D.', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"'),
        (v_competicion_id, 13, '2027-04-10', 'PEÑAS OSCENSES-C.D. Aramovil', 'JACETANO-C.F. Arok Sport'),
        (v_competicion_id, 13, '2027-04-10', 'HUESCA-S.D. ESCUELA DE FUTBOL', 'BINEFAR-FUTBOL BASE'),
        (v_competicion_id, 13, '2027-04-10', 'MONZON FUTBOL BASE - Mallazo', 'HUESCA-S.D.'),
        (v_competicion_id, 14, '2027-04-17', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"', 'SOBRARBE-ESCUELA DEP.'),
        (v_competicion_id, 14, '2027-04-17', 'JACETANO-C.F. Arok Sport', 'BARBASTRO-U.D.'),
        (v_competicion_id, 14, '2027-04-17', 'BINEFAR-FUTBOL BASE', 'PEÑAS OSCENSES-C.D. Aramovil'),
        (v_competicion_id, 14, '2027-04-17', 'HUESCA-S.D.', 'HUESCA-S.D. ESCUELA DE FUTBOL'),
        (v_competicion_id, 14, '2027-04-17', 'MONZON FUTBOL BASE - Mallazo', 'ALMUDEVAR A.D.'),
        (v_competicion_id, 15, '2027-04-24', 'ALMUDEVAR A.D.', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"'),
        (v_competicion_id, 15, '2027-04-24', 'SOBRARBE-ESCUELA DEP.', 'JACETANO-C.F. Arok Sport'),
        (v_competicion_id, 15, '2027-04-24', 'BARBASTRO-U.D.', 'BINEFAR-FUTBOL BASE'),
        (v_competicion_id, 15, '2027-04-24', 'PEÑAS OSCENSES-C.D. Aramovil', 'HUESCA-S.D.'),
        (v_competicion_id, 15, '2027-04-24', 'HUESCA-S.D. ESCUELA DE FUTBOL', 'MONZON FUTBOL BASE - Mallazo'),
        (v_competicion_id, 16, '2027-05-08', 'JACETANO-C.F. Arok Sport', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"'),
        (v_competicion_id, 16, '2027-05-08', 'BINEFAR-FUTBOL BASE', 'SOBRARBE-ESCUELA DEP.'),
        (v_competicion_id, 16, '2027-05-08', 'HUESCA-S.D.', 'BARBASTRO-U.D.'),
        (v_competicion_id, 16, '2027-05-08', 'MONZON FUTBOL BASE - Mallazo', 'PEÑAS OSCENSES-C.D. Aramovil'),
        (v_competicion_id, 16, '2027-05-08', 'HUESCA-S.D. ESCUELA DE FUTBOL', 'ALMUDEVAR A.D.'),
        (v_competicion_id, 17, '2027-05-15', 'JACETANO-C.F. Arok Sport', 'ALMUDEVAR A.D.'),
        (v_competicion_id, 17, '2027-05-15', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"', 'BINEFAR-FUTBOL BASE'),
        (v_competicion_id, 17, '2027-05-15', 'SOBRARBE-ESCUELA DEP.', 'HUESCA-S.D.'),
        (v_competicion_id, 17, '2027-05-15', 'BARBASTRO-U.D.', 'MONZON FUTBOL BASE - Mallazo'),
        (v_competicion_id, 17, '2027-05-15', 'PEÑAS OSCENSES-C.D. Aramovil', 'HUESCA-S.D. ESCUELA DE FUTBOL'),
        (v_competicion_id, 18, '2027-05-22', 'BINEFAR-FUTBOL BASE', 'JACETANO-C.F. Arok Sport'),
        (v_competicion_id, 18, '2027-05-22', 'HUESCA-S.D.', 'HUESCA INTERNATIONAL FOOTBALL ACADEMY "A"'),
        (v_competicion_id, 18, '2027-05-22', 'MONZON FUTBOL BASE - Mallazo', 'SOBRARBE-ESCUELA DEP.'),
        (v_competicion_id, 18, '2027-05-22', 'HUESCA-S.D. ESCUELA DE FUTBOL', 'BARBASTRO-U.D.'),
        (v_competicion_id, 18, '2027-05-22', 'ALMUDEVAR A.D.', 'PEÑAS OSCENSES-C.D. Aramovil');
    END IF;
END $$;
